sudo: false
branches:
  only:
  - master
env:
  global:
  - GH_REPO_REF: github.com/caro0o/Test
  - secure: IhN0PE/ihJw6xlrdmzUVP4BZZjAeKCchjZUGxTTJFAcdv6zbi88ZKSAySy0qwl52AMlCqo4AmyWWCXUMMvrZ5u0nQ8x0H9wdQVikdmSi0xKoKlnKa9cOfT/8fc9GaABbIg2MMaS4Et8LqHOIQoWgscAdL4ueKRCJ0JyzcOOLzXyIHX52bdT/+sN5SLTY8z413Dw041tkMSid/3B8zH363n1BpZXUPCcxe/bkgJdn9XfuoAOfz05Sv+fck4PrLY5jPOJ+JkNj+RsJdCR99hlJNN7ZhMXlGOJQ3lcr8m9DIEOY9sSHglH4MPTumNl+Y2rRC34W17B9ay6O4X5IYa712VmTukbLhKSxnBdU3OpFXfTynjPA8k4/Y1/uliwMwZfqUzARHy86bWGVqKtDcD9LeeITHNsCDslVNzq59mCqMCL4nZ3g74Rdf6PMNKrLdnpL6r5HRLqOSNNr2aao4pHXeEeZbwYHA48g5ESFBSmEzZ/KCMV5EDwStRNjX2Fxz+lenlNxLCBvaSY9l0Mm4ijUM9dvKOWg4NmYTajMyUntDFCknKuGzxhH9zJOkQFlJWBEbZZ6+rjgNqt+9sEHmbqhBbldyIezJSiHWbSCQaiOnErholbc1fPr+1mzJG20hZPG5Eg1dcAp9dOqRCk4rYh+sWOHM1TtUTkeZYK4bZjU6v0=
addons:
  apt:
    packages:
    - doxygen
    - doxygen-doc
    - doxygen-latex
    - doxygen-gui
    - graphviz
script:
- doxygen
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: "$GH_REPO_TOKEN"
  on: 
branch: master
