sudo: false
branches:
  only:
  - master
env:
  global:
  - GH_REPO_REF: github.com/caro0o/Test
  - secure: Kgn1U2xdpWXsr8SGuEKfGmswbI9xpoXkGDgZBms4r+5rGFAc8sH2UuIOUM0EYK5Kt9hSrc46IAmywl4QA57ZgjCLEgS326TVAcxq7CAp1VSayVm667SrUag+/zC+XvoGjN9wB8LZU0TXJFMIfUIfSzgBRuJ9oUnE+XanD48GEUXgZ5jOmJ70IfAIaCLkECdOPfjcHLADlo8FhtRkkAKmV+BJzklWVnZnzJTwOYnusoZqShz1J92LKSgY3Cm5Is7BmXkuD4DkVHPX+MVGuKVxgYxPaM/G1BjmJZOvTBnTket7qHmni5kuVmTdJNR6+fWxWn+cVUcajMSWD7ENMtuETaUCl+VdXpFX7oS6PpTD7vvUrldN1m/7qE/Xg/FvlULQ6zeMtfT7K0UIusYkdnG9gnESw7r7yvAMKGgioLGImZy734Kfbb36aLyayNXCbXnuw1YVgDP5B6u8VcjVghJ/lyfhYLN0d+KxAviyFkxPKxzyyUvyXk0BpbttVV3lJswPdk1qL2b9a660uOu/5ufcCVoAqeU//9BDFd8PF3zuicGuQUm9OsujZb4LW34bfQrDhustC/cAG0y6P195p2zB1oZy+jLBRFLlMLGLEBylI1yHwCJCLca8EvB73ayuVU1r5AiRWV47Fs9JdBO3O8IF2Go3xhnNxcendCkG/sXyc4w=
addons:
  apt:
    packages:
    - doxygen
    - doxygen-doc
    - doxygen-latex
    - doxygen-gui
    - graphviz
script:
- doxygen
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: "$secure"
  on: 
branch: master
