sudo: false
branches:
  only:
  - master
env:
  global:
  - GH_REPO_REF: github.com/caro0o/Test
addons:
  apt:
    packages:
    - doxygen
    - doxygen-doc
    - doxygen-latex
    - doxygen-gui
    - graphviz
script:
- doxygen
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: "$TRAVIS_BUILD_DIR/html"
  github_token: "$GITHUB_TOKEN"
  on: 
branch: master
