sudo: false
branches:
  only:
  - master
env:
  global:
  - GH_REPO_REF: github.com/caro0o/Test
  - secure: xN1eCGmzaBHhVHvM37lBIhxUcoS+nEGJnhqOMcEEblUobAYPnu21uRv5dfSEeeKSxk6QIp5WUSDFjufjkxWVnvvmFwLNl0GvmxBUcLrpTttvh4IWP2onLRuqSAAoRdrXJHU+Pk4Lg9BQbsNp9EHiiPFzltsTl0WxiJgOnkZleTzm5uWvHiGTM0CrNB8wr5iCOYmdQAORIa67vTnU0URptv8TDWiUPTespUvQ218qfCvzwRT0Y0t9kOIeMGOJYeQw8rBH4VyFi+uDjEBwNy6yI+3rRGwcO4vF/APaIzKZYBmUwJbkK+AMFA9Mmlmizn4lXKpPtaGzJAirMF4TQDjiqvWZaPD1xBXJMYSsOTfmxqFxtGUdsgmAHQkM+8DKqOJsgZmkwebfj1OI4uXaGdRAumNrfTr3rzznJ5WBLTNmyS9i3ZYnEXlHH1EAPiRt/dA/yZ8/Mwz8U04n/Dyf1frUAI0LUMPjIdAGnpWQJGfCtP+RxMHLIN7bUzkvNBfQUylqcsqxlVdITe/XP6QlLQHahWon624TSyuesQG9HoRI9ibDSApAZHQ9Mvd3V8GbR9XYDpCqQbIrhvkWt6K7HDKqhkIKJb8AZ670cGKjr3MM7IyWn1EuvrVSq5pucwlvFiaktLSKlun/nX4Yx940OQrDDRkLN1JcyYtzSLCYZsSrLpk=
addons:
  apt:
    packages:
    - doxygen
    - doxygen-doc
    - doxygen-latex
    - doxygen-gui
    - graphviz
script:
- doxygen
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: "$secure"
  on: 
branch: master
